name: Build PerformanceHUD IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Cập nhật lên v4

      - name: Install Theos
        run: |
          export THEOS=/Users/runner/work/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          # Tải SDK iOS 14.5
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz
          tar -xf iPhoneOS14.5.sdk.tar.xz -C $THEOS/sdks
          echo "THEOS=$THEOS" >> $GITHUB_ENV

      - name: Build Package
        run: |
          export THEOS=$THEOS
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # FIX LỖI Ở ĐÂY: Đã lên v4
        with:
          name: PerformanceHUD-IPA
          path: packages/*.ipa
